---
name: test
on: pull_request
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      update-khulnasoft-checksums: ${{steps.changes.outputs.update-khulnasoft-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
      go-mod-tidy: ${{steps.changes.outputs.go-mod-tidy}}
      test: ${{steps.changes.outputs.test}}
      update-readme: ${{steps.changes.outputs.update-readme}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            update-khulnasoft-checksums:
              - khulnasoft/khulnasoft.yaml
              - khulnasoft/imports/*.yaml
              - khulnasoft/khulnasoft-checksums.json
              - .github/workflows/test.yaml
              - .github/workflows/wc-update-khulnasoft-checksums.yaml
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/test.yaml
              - .github/workflows/wc-renovate-config-validator.yaml
            ghalint:
              - .github/workflows/*.yaml
              - khulnasoft/khulnasoft.yaml
              - khulnasoft/imports/ghalint.yaml
              - ghalint.yaml
            go-mod-tidy:
              - go.mod
              - go.sum
              - "**.go"
              - .github/workflows/test.yaml
              - .github/workflows/wc-go-mod-tidy.yaml
            test:
              - go.mod
              - go.sum
              - "**.go"
              - khulnasoft/imports/golangci-lint.yaml
              - .github/workflows/test.yaml
              - .github/workflows/wc-test.yaml
            update-readme:
              - README.md
              - docs/HEADER.md
              - docs/LIST.md
              - docs/FOOTER.md

  enable-automerge:
    uses: ./.github/workflows/wc-enable-auto-merge.yaml
    needs:
      - status-check
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped.
    # https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}

  enable-automerge-update-list:
    uses: ./.github/workflows/wc-enable-auto-merge.yaml
    needs:
      - status-check
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped.
    # https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && startsWith(github.head_ref, 'update-list-')
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}

  status-check:
    uses: ./.github/workflows/wc-status-check.yaml
    permissions: {}
    if: failure()
    needs:
      - renovate-config-validator
      - update-khulnasoft-checksums
      - ghalint
      - test
      - go-mod-tidy
      - update-readme

  renovate-config-validator:
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  update-khulnasoft-checksums:
    needs: path-filter
    if: needs.path-filter.outputs.update-khulnasoft-checksums == 'true'
    uses: ./.github/workflows/wc-update-khulnasoft-checksums.yaml
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}

  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: ./.github/workflows/wc-ghalint.yaml
    permissions: {}

  test:
    uses: ./.github/workflows/wc-test.yaml
    if: needs.path-filter.outputs.test == 'true'
    needs: path-filter
    permissions: {}

  update-readme:
    uses: ./.github/workflows/wc-update-readme.yaml
    if: needs.path-filter.outputs.update-readme == 'true'
    needs: path-filter
    permissions: {}
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}

  go-mod-tidy:
    uses: ./.github/workflows/wc-go-mod-tidy.yaml
    needs: path-filter
    if: needs.path-filter.outputs.go-mod-tidy == 'true'
    secrets:
      gh_app_id: ${{secrets.APP_ID_KHULNASOFTPROJ_KHULNASOFT}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY_KHULNASOFTPROJ_KHULNASOFT}}
    permissions:
      contents: read
