---
name: renovate-config-validator
on: workflow_call
jobs:
  renovate-config-validator:
    # Validate Renovate Configuration by renovate-config-validator.
    uses: sulaiman-coder/renovate-config-validator-workflow/.github/workflows/validate.yaml@35f1c78014c423fd37eb792c73f11ec0898098f4 # v0.2.2
    permissions:
      contents: read
